### ISSUE TITLE
Werbung/sozialeNW

### ISSUE THREAD

**Issue by maknoll** [Makerburg/Orga#3]
_From @theandrelf on April 28, 2015 11:32_

Wenn dann der Name feststeht (e.g. Makerburg), dann

- ~~Twitteraccount~~
- Domain registrieren
- ~~Website ausbauen~~ #10 
- Flyer/Poster basteln

_Copied from original issue: Makerburg/makerburg.de#9_

**Comment by maknoll** [comment]
https://twitter.com/makerburg

**Comment by maknoll** [comment]
_From @theandrelf on May 1, 2015 21:9_

Hab wegen Domain schon Andi angemailt. Würde er machen. Er braucht dann aber Name, Adresse und so.
Wäre vermutlich sinnvoll da einen von uns erstmal zu nehmen. Warten bis die Firma existiert finde ich etwas zu lange. Oder?

**Comment by theandrelf** [comment]
Kann man zumachen, oder?

**Comment by maknoll** [comment]
Jepp
