### ISSUE TITLE
Schraubstock

### ISSUE THREAD

**Issue by maknoll** [Makerburg/Orga#5]
_From @maknoll on April 25, 2015 22:15_

_Copied from original issue: Makerburg/makerburg.de#7_

**Comment by maknoll** [comment]
_From @theandrelf on May 1, 2015 21:6_

+ Maschinenschraubstock

**Comment by maknoll** [comment]
in welchem Preisrahmen soll sich der Schraubstock denn bewegen? Bei Ebay gehen die recht teuer weg.
Was sagt ihr zum Beispiel zu dem [hier](http://www.amazon.de/Brockhaus-Heuer-100-Parallel-Schraubstock-8-2057E/dp/B000VCZPR0/ref=sr_1_4?ie=UTF8&qid=1430587718&sr=8-4&keywords=schraubstock+heuer)?

**Comment by maknoll** [comment]
[Der hier](http://www.pollin.de/shop/dt/Nzc2ODk0OTk-/Werkstatt/Werkzeuge/Sonstiges/Tisch_Schraubstock_PTS_1500_mit_Amboss.html) bei Pollin ist herausragend günstig.

Maschinenschraubstöcke gibs günstig bei [Reichelt](http://www.reichelt.de/BS-60429/3/index.html?&ACTION=3&LA=446&ARTICLE=117550&artnr=BS+60429&SEARCH=Maschinenschraubstock).

**Comment by maknoll** [comment]
_From @theandrelf on May 3, 2015 19:46_

Der von Pollin sieht nach einem ziemlich guten Preis-Leistungsverhältnis aus.
Also: "ja" von mir zu dem von Pollin.
Ggfs. macht man ne (Netz39)Sammelbestellung um noch Versandkosten zu sparen.

**Comment by maknoll** [comment]
find ich gut.

**Comment by maknoll** [comment]
_From @theandrelf on May 3, 2015 20:7_

OK, dann schreib ich mal auf die N39-ML ob wer mit bei Pollin bestellen mag.

Den Maschinenschraubstock würde ich gleich bei Eric über die Reicheltsammelbestellung ordern. Falls Eric die Bestellung noch nicht rausgeschickt hat.

**Comment by Hichi** [comment]
Nein nicht closen....
Bin total gegen den von Pollin.
Lasst lieber den hier nehmen:
http://www.ebay.de/itm/Schraubstock-Amboss-360-drehbar-Drehteller-Werkbankschraubstock-Werkbank-150-mm-/311030577319?pt=LH_DefaultDomain_77&hash=item486addf8a7
-Schwerer
-Drehbar
-größere Spannbreite
-mit Versand nur 5€ teurer

**Comment by Hichi** [comment]
Habe den gerade gekauft und auf Katha bestellt:
http://www.ebay.de/itm/311030577319

**Comment by maknoll** [comment]
vorhanden
